// @ts-nocheck
import { useState } from "react";
import Head from "next/head";
import { encryptAES, decryptAES } from "../helpers/Des";
import { encryptTDES, decryptTDES } from "../helpers/TripleDES";

function Crypto() {
  const [algorithm, setAlgorithm] = useState("AES");
  const [decryptAlgorithm, setDecryptionAlgorithm] = useState("AES");
  const [text, setText] = useState("");
  const [encrypted, setEncryptedText] = useState(null);
  const [key, setKey] = useState("");

  const [encTextInput, setEncTextInput] = useState("");
  const [decKey, setDecKey] = useState("");
  const [decryptedText, setDecryptedText] = useState("");

  const handleInputChange = (event) => {
    setText(event.target.value);
  };

  const handleEncryption = () => {
    switch (algorithm) {
      case "AES":
        setEncryptedText(encryptAES(text, key));
        break;
      case "TripleDES":
        setEncryptedText(encryptTDES(text, key));
        break;
      case "OTP":
        setEncryptedText(encryptTDES(text, key));
        break;
      default:
        break;
    }
  };
  const handleDecryption = () => {
    //const decrText = decryptTDES(encTextInput, decKey);
    //setDecryptedText(decrText);
    switch (decryptAlgorithm) {
      case "AES":
        setDecryptedText(decryptAES(encTextInput, decKey));
        break;
      case "TripleDES":
        setDecryptedText(decryptTDES(encTextInput, decKey));
        break;
      case "OTP":
        setDecryptedText(decryptOTP(encTextInput, decKey));
        break;
      default:
        break;
    }
  };

  return (
    <div className="flex flex-col mx-0 bg-gray-900">
      <Head>
        <title>Crypto-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col md:px-36">
        <div className="flex justify-between shadow-sm border-b py-1">
          <div className="font-bold text-3xl text-blue-700">Crypto-app</div>
          <div className="font-semibold p-1 mx-2 text-sm text-blue-700">
            github
          </div>
        </div>
        <div className="flex flex-wrap md:flex-nowrap justify-center text-semibold my-10  ">
          <div className="w-full md:w-1/2 flex flex-col justify-center mx-2 mt-5 p-3 bg-gradient-to-br from-black via-red-400 to-red-700 border-2 border-gray-300">
            <div className="my-2 text-2xl text-red-600 font-mono font-bold">
              Encryption
            </div>
            <div className="flex mt-2">
              <label className="p-1 mx-2">Text</label>
              <textarea
                type="text"
                className="mx-2 mt-1 w-3/4 border focus:border-blue-500"
                onChange={(event) => handleInputChange(event)}
                value={text}
              />
            </div>
            <div className="flex mt-2">
              <label className="p-1 mx-2">Key</label>
              <input
                type="text"
                name="key"
                placeholder="..key"
                value={key}
                onChange={(event) => setKey(event.target.value)}
                className="mx-2 mt-1"
              />
              <label className="ml-3 p-1 m-2" s>
                Algorithm
              </label>
              <select
                id="Algo"
                name="Algo"
                className="mt-2"
                onChange={(event) => setAlgorithm(event.target.value)}
              >
                <option value="OPT">OPT</option>
                <option value="TripleDES">3DES</option>
                <option value="AES">AES</option>
              </select>
            </div>

            <button
              onClick={handleEncryption}
              className="my-4 mx-auto shadow-md shadow-red-300 rounded w-24 bg-blue-500 hover:bg-blue-600"
            >
              Encrypt
            </button>
            <textarea
              className="h-24 w-3/4 text-left mx-auto text-red-600 mt-2 pr-5 border p-1"
              value={encrypted}
            />
          </div>

          <div className="w-full md:w-1/2 flex flex-col justify-center mx-2 mt-5 p-3 bg-gradient-to-bl from-black via-red-400 to-red-700 border-2 border-gray-300">
            <div className="my-2 text-2xl text-red-600 font-mono font-bold">
              Decryption
            </div>
            <div className="flex mt-2">
              <label className="w-1/4 mt-1 mx-2">Encrypted Text</label>
              <textarea
                type="text"
                className="h-12 w-3/4 mx-2 mt-1 border focus:border-blue-500"
                value={encTextInput}
                onChange={(event) => setEncTextInput(event.target.value)}
              />
            </div>
            <div className="flex mt-2">
              <label className="w-1/4 p-1 mx-2">Key</label>
              <input
                type="text"
                name="decr_key"
                placeholder="..key"
                value={decKey}
                onChange={(event) => setDecKey(event.target.value)}
                className="w-3/4 mx-2 mt-1"
              />
              <label className="ml-3 p-1 m-2" s>
                Algorithm
              </label>
              <select
                id="Algo"
                name="Algo"
                className="mt-2"
                onChange={(event) => setDecryptionAlgorithm(event.target.value)}
              >
                <option value="OPT">OPT</option>
                <option value="TripleDES">3DES</option>
                <option value="AES">AES</option>
              </select>
            </div>

            <button
              onClick={handleDecryption}
              className="my-4 mx-auto shadow-md shadow-red-300 rounded w-24 bg-blue-500 hover:bg-blue-600"
            >
              Decrypt
            </button>

            <textarea
              className="font-semibold text-xl w-3/4 mx-auto mt-5 bg-gray-50 p-2"
              value={decryptedText}
            />
          </div>
        </div>
      </main>

      <footer className="flex h-24 justify-center bg-red-900">
        <a
          className="font-semibold text-gray-100"
          href="https://github.com/danmesfin"
        >
          Dan Mesfin
        </a>
      </footer>
    </div>
  );
}

export default Crypto;
